server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # API backend Node.js
    location /api/ {
        proxy_pass http://server:3000;
        proxy_set_header Host $host;
        proxy_read_timeout 300s;   # mo phong co the chay vai phut
    }

    # TiTiler - raster tiles
    location /tiles/ {
        rewrite ^/tiles/(.*)$ /$1 break;
        proxy_pass http://titiler:8000;
        proxy_set_header Host $host;
        add_header Cache-Control "public, max-age=3600";
    }
}
